### ISSUE TITLE
Wrong value of limiting resistor in ZMPT101B

### ISSUE THREAD

**Issue by MohammedBENHADINE** [openenergymonitor/emonVoltageSense#1]
Hey @glynhudson ,
I ve noticed that the ZMPT101B has a limit current of 2mA while the 60k limiting resistor will produce 230v/60k = 3.8mA .
Sorry if i'm mistaking something.
Regards,

**Comment by glynhudson** [comment]
Hi, well spotted, this is intentional. The ZMPT101B datasheet shows lower phase angle at higher current and a linear output voltage up to 8mA. At 4mA we've not observed any significant thermal effect, at 21 deg C ambient the case temperature is 36 deg C after running for about 7 days. 

![Screenshot from 2022-06-15 17-30-12](https://user-images.githubusercontent.com/758844/173878770-d595d821-6c26-46b9-9d50-706e2b0393d0.png)

**Comment by MohammedBENHADINE** [comment]
Waw fantastic, 
Thanks for the clarifications.

**Comment by MohammedBENHADINE** [comment]
@glynhudson Just another thought popped to my mind . 
For the sampling resistor , the  75 Ohm , this will give around 287mV at its borns , adding the 511mV bias , it will produce a swing wave between 917mV and 105mV , isn't that limiting to the precision of the overall ADC readings since we aren't taking advantage of the full 3v3 window of ADC ?

**Comment by andreid1303** [comment]
I'm confused about power ratings of the limiting resistors. By my calculations each one (of six) will desipate up to 150mW. Are they 0603 1/10W 50V?
